extends Node


class_name GameEnums


enum ROTATION_DIRECTION {
	LEFT, 
	RIGHT,
}

enum PIECE_ORIENTATION {
	ZERO_DEGREES, 
	NINTY_DEGREES, 
	ONEHUNDREDEIGHTY_DEGREES, 
	TWOSEVENTY_DEGREES,
}

enum PIECE_ROTATION_MOVEMENT {
	ZERO_TO_NINETY,
	NINETY_TO_ZERO,
	NINETY_TO_ONEHUNDREDEIGHTY,
	ONEHUNDREDEIGHTY_TO_NINETY,
	ONEHUNDREDEIGHTY_TO_TWOHUNDREDSEVENTY,
	TWOHUNDREDSEVENTY_TO_ONEHUNDREDEIGHTY,
	TWOHUNDREDSEVENTY_TO_ZERO,
	ZERO_TO_TWOHUNDREDSEVENTY,
}

